{"name": "test_auth1[firefox]", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'https://dev.smorodina.ru/partner/summary'\nActual value: https://dev.smorodina.ru/operators/authorization \nCall log:\n  - PageAssertions.to_have_url with timeout 5000ms\n  -   - waiting for locator(\":root\")\n  -     9 × locator resolved to <html lang=\"ru\" mode=\"md\" class=\"ion-ce plt-tablet plt-desktop md\">…</html>\n  -       - unexpected value \"https://dev.smorodina.ru/operators/authorization\"", "trace": "page = <Page url='https://dev.smorodina.ru/operators/authorization'>\nintercept_requests = [<Request url='https://dev.smorodina.ru/' method='GET'>, <Request url='https://api-maps.yandex.ru/v3/?apikey=c3134283-...0;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap' method='GET'>, ...]\n\n    @allure.feature('Клиент')\n    @allure.story('Авторизация клиента')\n    @allure.label('Успешный вход')\n    def test_auth1(page: Page, intercept_requests):  # Используем фикстуру\n    \n        assertions = Assertions(page)\n    \n        # Основной поток теста\n        with allure.step('Открыть главную'):\n            page.goto(URL)\n        with allure.step('Нажать \"Искать туры\"'):\n            page.get_by_role('button', name='Искать туры').click()\n        with allure.step('Нажать \"Войти\"'):\n            page.get_by_role('button', name='Войти').click()\n        with allure.step('Нажать \"Организатор туров\"'):\n            page.locator('//h4[text()=\"Организатор туров\"]').click()\n        with allure.step('Ввести email'):\n            page.fill('input[placeholder=\"email\"]', SELLER_LOGIN1)\n        with allure.step('Ввести пароль'):\n            page.fill('input[placeholder=\"пароль\"]', SELLER_PASSWORD1)\n        with allure.step('Нажать \"Войти\"'):\n            page.click('button[type=\"submit\"]')\n    \n        # Проверяем конечный URL после логина\n        with allure.step('Проверка url'):\n>           assertions.check_url(EXPECTED_URL_AFTER_LOGIN_SELLER)\n\ntests\\Client\\auth\\test_client_auth.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <data.assertions.Assertions object at 0x000001CB897A7F50>, expected_url = 'https://dev.smorodina.ru/partner/summary'\n\n    @allure.step('Проверка URL')\n    def check_url(self, expected_url: str):\n>       expect(self.page).to_have_url(expected_url)\nE       AssertionError: Page URL expected to be 'https://dev.smorodina.ru/partner/summary'\nE       Actual value: https://dev.smorodina.ru/operators/authorization \nE       Call log:\nE         - PageAssertions.to_have_url with timeout 5000ms\nE         -   - waiting for locator(\":root\")\nE         -     9 × locator resolved to <html lang=\"ru\" mode=\"md\" class=\"ion-ce plt-tablet plt-desktop md\">…</html>\nE         -       - unexpected value \"https://dev.smorodina.ru/operators/authorization\"\n\ndata\\assertions.py:12: AssertionError"}, "steps": [{"name": "Открыть главную", "status": "passed", "start": 1741180389932, "stop": 1741180391563}, {"name": "Нажать \"Искать туры\"", "status": "passed", "start": 1741180391563, "stop": 1741180392636}, {"name": "Нажать \"Войти\"", "status": "passed", "start": 1741180392636, "stop": 1741180392925}, {"name": "Нажать \"Организатор туров\"", "status": "passed", "start": 1741180392925, "stop": 1741180393072}, {"name": "Ввести email", "status": "passed", "start": 1741180393072, "stop": 1741180393128}, {"name": "Ввести пароль", "status": "passed", "start": 1741180393128, "stop": 1741180393168}, {"name": "Нажать \"Войти\"", "status": "passed", "start": 1741180393168, "stop": 1741180393296}, {"name": "Проверка url", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'https://dev.smorodina.ru/partner/summary'\nActual value: https://dev.smorodina.ru/operators/authorization \nCall log:\n  - PageAssertions.to_have_url with timeout 5000ms\n  -   - waiting for locator(\":root\")\n  -     9 × locator resolved to <html lang=\"ru\" mode=\"md\" class=\"ion-ce plt-tablet plt-desktop md\">…</html>\n  -       - unexpected value \"https://dev.smorodina.ru/operators/authorization\"\n\n", "trace": "  File \"F:\\Smorodina\\Autotests\\NikitaTimoshin1995-Smorodina_Autotests_Python_Playwright-1\\tests\\Client\\auth\\test_client_auth.py\", line 34, in test_auth1\n    assertions.check_url(EXPECTED_URL_AFTER_LOGIN_SELLER)\n    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"F:\\Smorodina\\Autotests\\NikitaTimoshin1995-Smorodina_Autotests_Python_Playwright-1\\data\\assertions.py\", line 12, in check_url\n    expect(self.page).to_have_url(expected_url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 18951, in to_have_url\n    self._sync(\n    ~~~~~~~~~~^\n        self._impl_obj.to_have_url(\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n            urlOrRegExp=url_or_reg_exp, timeout=timeout, ignoreCase=ignore_case\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        )\n        ^\n    )\n    ^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 127, in to_have_url\n    await self._expect_impl(\n    ...<4 lines>...\n    )\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n        f\"{out_message}\\nActual value: {actual} {format_call_log(result.get('log'))}\"\n    )\n"}, "steps": [{"name": "Проверка URL", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'https://dev.smorodina.ru/partner/summary'\nActual value: https://dev.smorodina.ru/operators/authorization \nCall log:\n  - PageAssertions.to_have_url with timeout 5000ms\n  -   - waiting for locator(\":root\")\n  -     9 × locator resolved to <html lang=\"ru\" mode=\"md\" class=\"ion-ce plt-tablet plt-desktop md\">…</html>\n  -       - unexpected value \"https://dev.smorodina.ru/operators/authorization\"\n\n", "trace": "  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"F:\\Smorodina\\Autotests\\NikitaTimoshin1995-Smorodina_Autotests_Python_Playwright-1\\data\\assertions.py\", line 12, in check_url\n    expect(self.page).to_have_url(expected_url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 18951, in to_have_url\n    self._sync(\n    ~~~~~~~~~~^\n        self._impl_obj.to_have_url(\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n            urlOrRegExp=url_or_reg_exp, timeout=timeout, ignoreCase=ignore_case\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        )\n        ^\n    )\n    ^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 127, in to_have_url\n    await self._expect_impl(\n    ...<4 lines>...\n    )\n  File \"C:\\Users\\Nikita\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n        f\"{out_message}\\nActual value: {actual} {format_call_log(result.get('log'))}\"\n    )\n"}, "parameters": [{"name": "expected_url", "value": "'https://dev.smorodina.ru/partner/summary'"}], "start": 1741180393296, "stop": 1741180398308}], "start": 1741180393296, "stop": 1741180398309}], "parameters": [{"name": "browser_name", "value": "'firefox'"}], "start": 1741180389932, "stop": 1741180398310, "uuid": "6353c827-a17a-4ce3-9be8-be65abfc502a", "historyId": "1d03f8c528918f97421303a7dc8061ed", "testCaseId": "f15c4d0bf8f787e145b7268779c306d4", "fullName": "tests.Client.auth.test_client_auth#test_auth1", "labels": [{"name": "story", "value": "Авторизация клиента"}, {"name": "feature", "value": "Клиент"}, {"name": "parentSuite", "value": "tests.Client.auth"}, {"name": "suite", "value": "test_client_auth"}, {"name": "host", "value": "DESKTOP-7M1TI5K"}, {"name": "thread", "value": "14496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Client.auth.test_client_auth"}]}